# FreeBSD website

baseURL = "https://www-dev.freebsd.org"
title = "The FreeBSD Project"
copyright = "BSD 2-clause 'Simplified' License"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
theme = "beastie"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
disableLanguages = ["tr", "el"]
disablePathToLower = true
authors = [ "carlavilla@FreeBSD.org" ]

preserveTOC = true

[markup.asciidocExt]
    preserveTOC = true

staticDir = ["static", "shared"]

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
list = [ "HTML" ]
single = [ "HTML" ]
section = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.Calendar]
BaseName = "calendar"
IsHTML = true
IsPlainText = false

[outputFormats.RSS]
MediaType = "application/rss+xml"
BaseName = "feed"
IsHTML = true
IsPlainText = false
noUgly = true
Rel = "alternate"
